spring:
  datasource:
    url: jdbc:postgresql://ec2-3-231-16-122.compute-1.amazonaws.com:5432/d6fuheemue4uul
    username: dewfcanwqnhmnz
    password: 6bc2de3321aa5e09406be9fe88424bd3e5877bcc2226eda643eaee5bd7f4581f

  flyway:
    enabled: true
    clean-disabled: true

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

server:
  servlet:
    context-path: /api
  port: 8083

ratesapi:
  url: https://api.ratesapi.io/api