spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: postgres
    password: 123456

  flyway:
    enabled: true
    clean-disabled: false

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

server:
  servlet:
    context-path: /api
  port: 8083

ratesapi:
  url: https://api.ratesapi.io/api